drop table IFS_APP_DTL ;

drop table IFS_ORG;

drop table IFS_BAT_CLEAR;

drop table IFS_BAT_JOB_INF;

drop table IFS_BAT_LOAD_INF;

drop table IFS_BAT_PROC;

drop table IFS_BAT_PROC_LOG;

drop table IFS_BAT_PROC_STATUS;

drop table IFS_BAT_PROC_STEP;

drop table IFS_BAT_SUB_PROC_LOG;

drop table IFS_BAT_SUB_PROC_STEP;

drop table IFS_BAT_WARNING_LOG;

drop table IFS_NATION_INF;

drop table IFS_STAFF_FAV;

drop table IFS_DATA_DIC;

drop table IFS_MENU_INF;

drop table IFS_SYS_INF;

drop table IFS_CAL_INF;

drop table IFS_PWD_HIS;

drop table IFS_SYS_PARAM;

drop table IFS_RES_INF;

drop table IFS_ROLE;

drop table IFS_SER_NUM;

drop table IFS_CUR_INF;

drop table IFS_CUR_RATE;

drop table IFS_CHK_TASK;

drop table IFS_CHK_TASK_LOG;

drop table IFS_CRON_JOB;

drop table IFS_CRON_JOB_LOG;

drop table IFS_BIZ_LOG;

drop table IFS_EXP_TASK_INF;

drop table IFS_ORG_REL;

drop table IFS_STAFF;

drop table IFS_LOGIN_LOG;

drop table IFS_STAFF_ROLE_REL;

drop table IFS_QRZ_JOB_LOG;

drop table IFS_PAGE_TYPE;

drop table IFS_PAGE_OPT_ITEM;

drop table IFS_PAGE_OPT_DTL;

drop table IFS_PAGE_ITEM;

drop table IFS_PAGE_DTL;

CREATE TABLE
    IFS_APP_DTL
    (
        ID CHAR(32) NOT NULL,
        CONTRACTNO VARCHAR2(20),
        APPNO VARCHAR2(20),
        TXN_DATE CHAR(8),
        BRCODE VARCHAR2(4),
        TLSRNO VARCHAR2(20),
        AUTO_FLAG CHAR(1),
        APPROVER VARCHAR2(8),
        AUTO_APPROVER CHAR(1),
        FUNC_CODE VARCHAR2(10),
        APPTYPE CHAR(2),
        ATTITUDE CHAR(1),
        ROLE_ID INTEGER,
        MEETING_FLAG CHAR(1),
        MISC VARCHAR2(256),
        LAST_UPD_TLR VARCHAR2(8),
        LAST_UPD_DATE CHAR(8),
        LAST_UPD_FUNC VARCHAR2(20),
        CINO VARCHAR2(32),
        UNTREAD CHAR(1),
        REASON VARCHAR2(4000),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_ORG
    (
        BRCODE CHAR(4) NOT NULL,
        BRNO VARCHAR2(20) NOT NULL,
        BRNAME VARCHAR2(60),
        BRCLASS CHAR(1),
        BRATTR CHAR(1),
        BLN_BRANCH_CLASS CHAR(1),
        BLN_BRANCH_BRCODE CHAR(4),
        BLN_MANAGE_BRCODE CHAR(4),
        BLN_UP_BRCODE CHAR(4),
        TXN_BRCODE CHAR(4),
        AUTHLVL CHAR(1),
        LINKMAN VARCHAR2(20),
        TELENO CHAR(20),
        ADDRESS VARCHAR2(60),
        POSTNO CHAR(6),
        OTHER_AREA_FLAG CHAR(1),
        REGIONALISM CHAR(6),
        FINANCE_CODE CHAR(14),
        STATUS CHAR(1),
        MISCFLGS CHAR(20),
        MISC VARCHAR2(256),
        LAST_UPD_TLR VARCHAR2(8),
        LAST_UPD_FUNC VARCHAR2(20),
        LAST_UPD_DATE CHAR(8),
		ST CHAR(1),
        IS_LOCK CHAR(1),
        IS_DEL CHAR(1),
        PRIMARY KEY (BRCODE)
    );
CREATE TABLE
    IFS_BAT_CLEAR
    (
        TABLE_SEQ INTEGER NOT NULL,
        TABLE_ENG VARCHAR2(30) NOT NULL,
        TABLE_CHN VARCHAR2(60) NOT NULL,
        CLEAN_INTERVAL VARCHAR2(30) NOT NULL,
        RUNTIME CHAR(2) NOT NULL,
        DATE_FIELD VARCHAR2(30),
        CLEAR_CONDITION VARCHAR2(200),
        COMMIT_CNT INTEGER NOT NULL,
        FLAG CHAR(1) NOT NULL,
        JOBNO INTEGER NOT NULL,
        MODE_TYPE CHAR(1),
        BACKUP_FLAG CHAR(1) NOT NULL,
        DESC_TX VARCHAR2(1024),
        LAST_UPD_TS CHAR(17),
        PRIMARY KEY (TABLE_SEQ)
    );
CREATE TABLE
    IFS_BAT_JOB_INF
    (
        JOBNO INTEGER NOT NULL,
        PRE_JOBNO INTEGER,
        PRE_AUTORUN CHAR(1),
        SYSTEM_TYPE CHAR(2),
        RUNONLINE CHAR(2),
        TIMESTAMPS CHAR(17),
        MISCFLGS VARCHAR2(256),
        MISC VARCHAR2(256),
        PRIMARY KEY (JOBNO)
    );
CREATE TABLE
    IFS_BAT_LOAD_INF
    (
        ID INTEGER NOT NULL,
        TABLE_NAME VARCHAR2(30) NOT NULL,
        LOAD_TYPE CHAR(1) NOT NULL,
        LAST_UPD_DT INTEGER DEFAULT 0,
        KEYWORD VARCHAR2(50) DEFAULT ' ',
        IS_UPLOAD CHAR(1) DEFAULT '0',
        TABLE_SPACE_NAME CHAR(30) DEFAULT ' ',
        DESCS VARCHAR2(256),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_BAT_PROC
    (
        BHDATE CHAR(8) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        RESUME_POINT CHAR(60),
        PROC_VALUE VARCHAR2(1024),
        PRIMARY KEY (BHDATE, JOBNO, STEP, SUB_STEP)
    );
CREATE TABLE
    IFS_BAT_PROC_LOG
    (
        ID NUMBER(6) NOT NULL,
        BHDATE CHAR(8) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        PROCESS_FUNCTION CHAR(120),
        PROCESSID INTEGER,
        START_TIME CHAR(17),
        END_TIME CHAR(17),
        STATUS CHAR(1),
        TIMESTAMPS CHAR(17),
        ERR_MSG VARCHAR2(1024),
        DESC1 VARCHAR2(1024),
        DESC2 VARCHAR2(1024),
        PRIMARY KEY (ID),
        UNIQUE (SUB_STEP, STEP, JOBNO, BHDATE)
    );
CREATE TABLE
    IFS_BAT_PROC_STATUS
    (
        ID NUMBER(6) NOT NULL,
        BHDATE CHAR(8) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        PROCESS_FUNCTION VARCHAR2(120),
        PROCESSID INTEGER,
        START_TIME CHAR(17),
        END_TIME CHAR(17),
        SUB_FLAG CHAR(1),
        STATUS CHAR(1),
        BRANCHLIST VARCHAR2(1024),
        DESC1 VARCHAR2(1024),
        DESC2 VARCHAR2(1024),
        TIMESTAMPS CHAR(17),
        PRIMARY KEY (ID),
        UNIQUE (JOBNO, BHDATE)
    );
CREATE TABLE
    IFS_BAT_PROC_STEP
    (
        ID NUMBER(6) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        PROCESS_FUNCTION CHAR(120) NOT NULL,
        PROCESS_PARAM VARCHAR2(512),
        PROCESS_TLRNO CHAR(7),
        RUNTIME CHAR(2),
        SUB_FLAG CHAR(1),
        MAXPROC INTEGER,
        TEMP_FLAG CHAR(1),
        SUSPEND CHAR(1),
        AUTO CHAR(1),
        TIMESTAMPS CHAR(17),
        DESC0 VARCHAR2(128),
        DESC1 VARCHAR2(1024),
        DESC2 VARCHAR2(1024),
        REPORT_FLAG VARCHAR2(10),
        REPORT_DATA_FLAG CHAR(1),
        REPEAT_CNT INTEGER,
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_BAT_SUB_PROC_LOG
    (
        ID NUMBER(6) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        FUNC_STEP INTEGER NOT NULL,
        SUB_PROCE_FUNCTION CHAR(120),
        BHDATE CHAR(8) NOT NULL,
        BREAK_POINT VARCHAR2(1024),
        STATUS CHAR(1),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_BAT_SUB_PROC_STEP
    (
        ID NUMBER(6) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        FUNC_STEP INTEGER NOT NULL,
        SUB_PROCE_FUNCTION CHAR(120),
        RUNTIME CHAR(2),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_BAT_WARNING_LOG
    (
        ID NUMBER(6) NOT NULL,
        TXDATE CHAR(8) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        CONTRACTNO CHAR(20),
        PERI INTEGER,
        MSG VARCHAR2(1024),
        LINE VARCHAR2(1024),
        TIMESTAMPS CHAR(17),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_NATION_INF
    (
        NATIONREGION_CODE VARCHAR2(10) NOT NULL,
        CHINA_NAME VARCHAR2(128),
        NATIONREGION_NUMBER VARCHAR2(10),
        CHINA_SHORT_NAME VARCHAR2(128),
        ENG_NAME VARCHAR2(128),
        ENG_SHORT_NAME VARCHAR2(128),
        ST CHAR(1),
        IS_LOCK CHAR(1),
        IS_DEL CHAR(1),
        CRT_DT CHAR(8),
        LAST_UPD_TMS VARCHAR2(14),
        LAST_UPD_OPER VARCHAR2(20),
        PRIMARY KEY (NATIONREGION_CODE)
    );
CREATE TABLE
    IFS_STAFF_FAV
    (
        ID VARCHAR2(32) NOT NULL,
        TLR_NO VARCHAR2(20),
        FUNC_ID VARCHAR2(20),
        SHOW_SEQ INTEGER,
        FUNC_TYPE VARCHAR2(20),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_DATA_DIC
    (
        ID VARCHAR2(32) NOT NULL,
        DATA_TYPE_NO INTEGER NOT NULL,
        DATA_NO VARCHAR2(20) NOT NULL,
        DATA_TYPE_NAME VARCHAR2(60),
        DATA_NO_LEN INTEGER,
        DATA_NAME VARCHAR2(150),
        LIMIT_FLAG CHAR(1),
        HIGH_LIMIT VARCHAR2(20),
        LOW_LIMIT VARCHAR2(40),
        MISCFLGS VARCHAR2(20),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_MENU_INF
    (
        FUNCID VARCHAR2(20) NOT NULL,
        FUNCNAME VARCHAR2(60),
        PAGEPATH VARCHAR2(250),
        LOCATION INTEGER,
        ISDIRECTORY INTEGER,
        LASTDIRECTORY VARCHAR2(20),
        SHOWSEQ INTEGER,
        FUNC_CLASS CHAR(1),
        FUNC_TYPE CHAR(1),
        WORKFLOW_FLAG CHAR(1),
        UP_FUNC_CODE CHAR(10),
        FUNC_DESC VARCHAR2(60),
        STATUS CHAR(1),
        MISCFLGS CHAR(20),
        MISC VARCHAR2(1024),
        ICON_CLS VARCHAR2(256),
        PRIMARY KEY (FUNCID)
    );
CREATE TABLE
    IFS_SYS_INF
    (
        ID NUMBER(6) NOT NULL,
        SYSTEM_NAME VARCHAR2(20),
        TBSDY CHAR(8),
        BHDATE CHAR(8),
        LBHDATE CHAR(8),
        STATUS CHAR(1),
        SYSTEM_TYPE CHAR(2),
        MISCFLGS VARCHAR2(20),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_CAL_INF
    (
        ID CHAR(32) NOT NULL,
        YEAR INTEGER,
        HOLIDAY_DEF VARCHAR2(366),
        LAST_UPD_OPER_ID VARCHAR2(32),
        LAST_UPD_TIME CHAR(14),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_PWD_HIS
    (
        ID VARCHAR2(32) NOT NULL,
        USERID VARCHAR2(32) NOT NULL,
        PASSWORD VARCHAR2(100) NOT NULL,
        ENC_MODE VARCHAR2(10),
        MODIFIED_TIME CHAR(14) NOT NULL,
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_SYS_PARAM
    (
        PARAM_ID VARCHAR2(4) NOT NULL,
        MAGIC_ID VARCHAR2(20) NOT NULL,
        PARAM_START_TM CHAR(8),
        PARAM_END_TM CHAR(8),
        PARAM_CHANG_FLAG CHAR(1),
        PARAM_VALUE_TX VARCHAR2(512),
        LAST_UPD_TLR CHAR(8),
        LAST_UPD_FUNC VARCHAR2(20),
        LAST_UPD_DATE CHAR(8),
        DESC0 VARCHAR2(256),
        ST CHAR(1),
        IS_LOCK CHAR(1),
        IS_DEL CHAR(1),
        PRIMARY KEY (PARAM_ID, MAGIC_ID)
    );
CREATE TABLE
    IFS_RES_INF
    (
        ID CHAR(32) NOT NULL,
        ROLE_ID INTEGER,
        FUNCID VARCHAR2(20),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_ROLE
    (
        ROLE_ID INTEGER NOT NULL,
        ROLE_NAME VARCHAR2(30),
        STATUS CHAR(1),
        EFFECT_DATE CHAR(8),
        EXPIRE_DATE CHAR(8),
        BRCLASS CHAR(1),
        MISCFLGS CHAR(20),
        MISC VARCHAR2(256),
        ROLE_TYPE CHAR(1),
        IS_LOCK CHAR(1),
        CRT_DT CHAR(8),
        LAST_UPD_TMS VARCHAR2(14),
        LAST_UPD_OPER VARCHAR2(20),
        ST CHAR(1),
        PRIMARY KEY (ROLE_ID)
    );
CREATE TABLE
    IFS_SER_NUM
    (
        ID CHAR(32) NOT NULL,
        VALUE_NO INTEGER DEFAULT 0,
        VALUE_INDEX VARCHAR2(40),
        VALUE_CURR INTEGER,
        MAX_VALUE INTEGER,
        MIN_VALUE INTEGER,
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_CUR_INF
    (
        CURCD VARCHAR2(6) NOT NULL,
        CNNAME VARCHAR2(52),
        ST CHAR(1),
        IS_LOCK CHAR(1),
        IS_DEL CHAR(1),
        CREATE_DATE CHAR(8),
        LAST_UPD_DATE CHAR(8),
        LAST_UPD_TLR VARCHAR2(20),
        SHOWSEQ NUMBER(22),
        ISUSD CHAR(1),
        ENNAME VARCHAR2(20),
        CURSYMBOL VARCHAR2(20),
        CREATE_TLR VARCHAR2(20),
        BASE_UNIT VARCHAR2(4),
        MIN_UNIT VARCHAR2(4),
        CUR_EDICD CHAR(3),
        CUR_EDINAME VARCHAR2(25),
        CURNO VARCHAR2(6),
        DRATEDAYS CHAR(1),
        PRIMARY KEY (CURCD)
    );
CREATE TABLE
    IFS_CUR_RATE
    (
        ID VARCHAR2(32) NOT NULL,
        CURCD CHAR(3) NOT NULL,
        CURRRATE_DATE CHAR(8) NOT NULL,
        LAST_UPD_DATE CHAR(8),
        LAST_UPD_TLR VARCHAR2(8),
        TO_CURCD CHAR(3) NOT NULL,
        BUY_RATE NUMBER(16,3),
        SELL_RATE NUMBER(16,3),
        EXCHG_RATE NUMBER(16,3),
        CONSTRAINT PK_SYSCURRRATE PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_CHK_TASK
    (
        TSK_ID CHAR(14) NOT NULL,
        INT_OPER_ID VARCHAR2(20),
        INS_CD VARCHAR2(20),
        INT_INS_ID VARCHAR2(10),
        ADT_RCD_PK VARCHAR2(32),
        UPD_TRANS_CD CHAR(2),
        CRT_DT CHAR(8),
        LAST_UPD_OPER VARCHAR2(20),
        LAST_UPD_TMS VARCHAR2(14),
        NEW_VAL1 VARCHAR2(2048),
        NEW_VAL2 VARCHAR2(2048),
        OLD_ST CHAR(1),
        PRIMARY KEY (TSK_ID)
    );
CREATE TABLE
    IFS_CHK_TASK_LOG
    (
        TSK_ID CHAR(14) NOT NULL,
        INT_OPER_ID VARCHAR2(20),
        INS_CD VARCHAR2(20),
        INT_INS_ID VARCHAR2(10),
        ADT_RCD_PK VARCHAR2(32),
        UPD_TRANS_CD CHAR(2),
        CRT_DT CHAR(8),
        LAST_UPD_OPER VARCHAR2(20),
        LAST_UPD_TMS VARCHAR2(14),
        NEW_VAL1 VARCHAR2(2048),
        NEW_VAL2 VARCHAR2(2048),
        APPROVE_RESULT CHAR(2),
        APPROVE_OPER_ID VARCHAR2(20),
        APPROVE_INS_CD VARCHAR2(20),
        APPROVE_TM VARCHAR2(14),
        APPROVE_REMARK VARCHAR2(256),
        OLD_VAL1 VARCHAR2(2048),
        OLD_VAL2 VARCHAR2(2048),
        PRIMARY KEY (TSK_ID)
    );
CREATE TABLE
    IFS_BIZ_LOG
    (
        ID CHAR(36) NOT NULL,
        LOG_ID CHAR(36) NOT NULL,
        TXN_DATE CHAR(8) NOT NULL,
        TXN_START_TIME CHAR(6) NOT NULL,
        TXN_END_TIME CHAR(6) NOT NULL,
        TXN_RUN_TIME NUMBER NOT NULL,
        BRCODE CHAR(20),
        OPRCODE CHAR(20),
        IP_ADR VARCHAR2(20),
        FUNCID VARCHAR2(20),
        OPRTXNCD VARCHAR2(100),
        TXN_BIZ_LOG1 VARCHAR2(2048),
        TXN_BIZ_LOG2 VARCHAR2(2048),
        TXN_STATUS CHAR(2),
        TXN_FAIL_LOG VARCHAR2(2048),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_EXP_TASK_INF
    (
        TSK_ID CHAR(36) NOT NULL,
        TSK_NM VARCHAR2(50),
        TSK_START_TMS CHAR(14),
        TSK_START_OP VARCHAR2(40),
        TSK_DESC VARCHAR2(60),
        TSK_PARAM1 VARCHAR2(2048),
        TSK_PARAM2 VARCHAR2(2048),
        TSK_OWNER VARCHAR2(40),
        TSK_END_TMS CHAR(14),
        TSK_RUN_CLASS CHAR(2),
        EXP_FILE_NM VARCHAR2(128),
        EXP_RCD_NUM NUMBER,
        EXP_RCD_SUM_NUM NUMBER,
        EXP_FILE_SIZE NUMBER,
        TSK_STAT CHAR(1),
        PRIMARY KEY (TSK_ID)
    );
CREATE TABLE
    IFS_ORG_REL
    (
        ID CHAR(32) NOT NULL,
        TLR_NO VARCHAR2(20),
        BR_NO VARCHAR2(20),
        PRIMARY KEY (ID)
    );
CREATE TABLE
    IFS_STAFF
    (
        TLRNO VARCHAR2(20) NOT NULL,
        TLR_NAME VARCHAR2(30),
        TLR_TYPE CHAR(1),
		EMAIL VARCHAR2(40),
        BRCODE CHAR(4),
        PASSWORD VARCHAR2(50),
        STATUS CHAR(1),
		ROLEID INTEGER,
		MSRNO INTEGER,
		FLAG CHAR(1),
		LOGIN_IP VARCHAR2(20),
		SESSION_ID VARCHAR2(256),
        CHEK_DPWD_FLG CHAR(1),
		CREATE_DATE CHAR(8),
        LASTACCESSTM CHAR(14),
		LASTLOGOUTTM  CHAR(14),
		LASTPWDCHGTM CHAR(14),
		LASTFAILEDTM CHAR(14),
        PSWDERRCNT INTEGER,
        TOTPSWDERRCNT INTEGER,
        PSWDERRDATE CHAR(8),
        PASSWDENC VARCHAR2(10),
        FAILMAXLOGIN INTEGER,
        PASSWDCHGINTERVAL INTEGER,
        PASSWDWARNINTERVAL INTEGER,
        IS_LOCK CHAR(1),
        LOCK_REASON VARCHAR2(200),
        IS_LOCK_MODIFY CHAR(1),
        CRT_DT CHAR(8),
        LAST_UPD_TMS VARCHAR2(14),
        LAST_UPD_OPER VARCHAR2(20),
        ST CHAR(1),
        PRIMARY KEY (TLRNO)
    );
CREATE TABLE
    IFS_LOGIN_LOG
    (
        LOG_ID VARCHAR2(32) NOT NULL,
        TLR_NO VARCHAR2(20),
        BR_NO VARCHAR2(20),
        LOGIN_SUC_TM CHAR(14),
        LOGIN_OUT_TM CHAR(14),
        LOGIN_FAIL_TM CHAR(14),
        LOGIN_ADDR VARCHAR2(20),
        LOGIN_REMARK VARCHAR2(256),
        SESSION_ID VARCHAR2(256),
        CRT_TM CHAR(14),
        PRIMARY KEY (LOG_ID)
    );
CREATE TABLE
    IFS_STAFF_ROLE_REL
    (
        ID CHAR(32) NOT NULL,
        TLRNO VARCHAR2(20),
        ROLE_ID INTEGER,
        STATUS CHAR(1),
        PRIMARY KEY (ID)
    );
CREATE TABLE 
    IFS_CRON_JOB
    (
        ID VARCHAR2(32) NOT NULL,
        JOBNO INTEGER NOT NULL,
        PROCESS_FUNCTION VARCHAR2(256) NOT NULL,
        PROCESS_PARAM VARCHAR2(512),
        MAXPROC INTEGER,
        RUNTIME CHAR(2),
        DAYS_OF_MONTH INTEGER,
        REPEAT_TIME NUMBER,
        REPEAT_CNT INTEGER,
        START_TIME CHAR(6),
        END_TIME CHAR(6),
        LAST_RUN_TIME CHAR(14),
        DUE_TIME CHAR(14),
        SUC_FLAG CHAR(1),
        FAIL_FLAG CHAR(1),
        AUTO CHAR(1),
        LOCK_OWN VARCHAR2(10),
        DESC0 VARCHAR2(128),
        DESC1 VARCHAR2(1024),
        DESC2 VARCHAR2(1024),
        TIMESTAMPS CHAR(14),
        DUALCONTROL_LOCKSTATUS VARCHAR2(1),
        PRIMARY KEY (ID)
    );

CREATE TABLE 
    IFS_CRON_JOB_LOG
    (
        ID VARCHAR2(32) NOT NULL,
        JOBNO INTEGER NOT NULL,
        SUB_PROCE_FUNCTION VARCHAR2(256) NOT NULL,
        EXCUTE_TIME CHAR(14),
        EXCUTE_RESULT CHAR(1),
        EXCUTE_OWN VARCHAR2(10),
        FAIL_FLAG CHAR(1),
        SUC_FLAG CHAR(1),
        EXCEPTION_MSG VARCHAR2(512),
        END_EXCUTE_FLAG CHAR(1),
        PRIMARY KEY (ID)
    );

CREATE TABLE
    IFS_QRZ_JOB_LOG
    (
        LOG_ID VARCHAR2(32) NOT NULL,
        QUARTZ_ID VARCHAR2(32),
        EXEC_TM DATE,
        END_TM DATE,
        QUARTZ_NAME VARCHAR2(128),
        QUARTZ_RESULT CHAR(2),
        REMARK VARCHAR2(1024),
        PRIMARY KEY (LOG_ID)
    );
CREATE TABLE IFS_PAGE_TYPE 
(
    ID CHAR(32) NOT NULL,
    NAME VARCHAR2(256) NOT NULL,
    DESC_INFO VARCHAR2(512) NOT NULL,
    TYPE CHAR(1) NOT NULL,
    PARENT CHAR(32) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    LAST_UPD_TLR VARCHAR2(20) NULL,
    LAST_UPD_TS VARCHAR2(17) NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IFS_PAGE_OPT_ITEM 
(
    ID CHAR(32) NOT NULL,
    NAME VARCHAR2(256) NOT NULL,
    DESC_INFO VARCHAR2(512) NOT NULL,
    VIEWTYPE CHAR(1) NOT NULL,
    TYPEID CHAR(32) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    LAST_UPD_TLR VARCHAR2(20) NULL,
    LAST_UPD_TS VARCHAR2(17) NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IFS_PAGE_OPT_DTL 
(
    ID CHAR(32) NOT NULL,
    NAME VARCHAR2(256) NOT NULL,
    DESC_INFO VARCHAR2(512) NOT NULL,
    OPERATION CHAR(1) NOT NULL,
    OPT_CLAZZ VARCHAR2(256) NULL,
    OPT_SCRIPT VARCHAR2(1024) NULL,
    DEFAULT_CQID VARCHAR2(64) NULL,
    PARENT CHAR(32) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    SEQID CHAR(3) NOT NULL,
    LAST_UPD_TLR VARCHAR2(20) NULL,
    LAST_UPD_TS VARCHAR2(17) NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE IFS_PAGE_ITEM 
(
    ID CHAR(32) NOT NULL,
    NAME VARCHAR2(256) NOT NULL,
    DESC_INFO VARCHAR2(512) NOT NULL,
    TYPEID CHAR(36) NOT NULL,
    VIEWTYPE CHAR(1) NOT NULL,
    DEFAULTNO CHAR(32) NOT NULL,
    OP_ITEM_ID CHAR(32) NULL,
    STATUS CHAR(1) NOT NULL,
    LAST_UPD_TS VARCHAR2(17) NULL,
    LAST_UPD_TLR VARCHAR2(20) NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE IFS_PAGE_DTL 
(
    ID CHAR(32) NOT NULL,
    NAME VARCHAR2(256) NOT NULL,
    DESC_INFO VARCHAR2(512) NOT NULL,
    PAGFE_URL VARCHAR2(256) NOT NULL,
    PARAM_LIST VARCHAR2(512) NULL,
    PARENT CHAR(32) NOT NULL,
    SEQID CHAR(3) NULL,
    OPT_DETAILS VARCHAR2(512) NULL,
    STATUS CHAR(1) NOT NULL,
    LAST_UPD_TLR VARCHAR2(20) NULL,
    LAST_UPD_TS VARCHAR2(17) NULL,
    PRIMARY KEY (ID)
);
